# Generated by Django 5.0.7 on 2024-07-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('code', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
