# Generated by Django 5.0.7 on 2024-07-21 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'ordering': ['-created_time']},
        ),
    ]
