# Generated by Django 5.0.7 on 2024-07-30 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
